// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: tele_service.proto
#ifndef GRPC_tele_5fservice_2eproto__INCLUDED
#define GRPC_tele_5fservice_2eproto__INCLUDED

#include "tele_service.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class tele_service final {
 public:
  static constexpr char const* service_full_name() {
    return "tele_service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status get_if_list(::grpc::ClientContext* context, const ::empty_request& request, ::getif_response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::getif_response>> Asyncget_if_list(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::getif_response>>(Asyncget_if_listRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::getif_response>> PrepareAsyncget_if_list(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::getif_response>>(PrepareAsyncget_if_listRaw(context, request, cq));
    }
    virtual ::grpc::Status run_capture(::grpc::ClientContext* context, const ::run_cap_request& request, ::run_cap_response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::run_cap_response>> Asyncrun_capture(::grpc::ClientContext* context, const ::run_cap_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::run_cap_response>>(Asyncrun_captureRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::run_cap_response>> PrepareAsyncrun_capture(::grpc::ClientContext* context, const ::run_cap_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::run_cap_response>>(PrepareAsyncrun_captureRaw(context, request, cq));
    }
    virtual ::grpc::Status get_cap_status(::grpc::ClientContext* context, const ::empty_request& request, ::get_cap_status_response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::get_cap_status_response>> Asyncget_cap_status(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::get_cap_status_response>>(Asyncget_cap_statusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::get_cap_status_response>> PrepareAsyncget_cap_status(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::get_cap_status_response>>(PrepareAsyncget_cap_statusRaw(context, request, cq));
    }
    virtual ::grpc::Status get_topk_result(::grpc::ClientContext* context, const ::empty_request& request, ::get_topk_result_response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::get_topk_result_response>> Asyncget_topk_result(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::get_topk_result_response>>(Asyncget_topk_resultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::get_topk_result_response>> PrepareAsyncget_topk_result(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::get_topk_result_response>>(PrepareAsyncget_topk_resultRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void get_if_list(::grpc::ClientContext* context, const ::empty_request* request, ::getif_response* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void get_if_list(::grpc::ClientContext* context, const ::empty_request* request, ::getif_response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void get_if_list(::grpc::ClientContext* context, const ::empty_request* request, ::getif_response* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void run_capture(::grpc::ClientContext* context, const ::run_cap_request* request, ::run_cap_response* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void run_capture(::grpc::ClientContext* context, const ::run_cap_request* request, ::run_cap_response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void run_capture(::grpc::ClientContext* context, const ::run_cap_request* request, ::run_cap_response* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void get_cap_status(::grpc::ClientContext* context, const ::empty_request* request, ::get_cap_status_response* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void get_cap_status(::grpc::ClientContext* context, const ::empty_request* request, ::get_cap_status_response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void get_cap_status(::grpc::ClientContext* context, const ::empty_request* request, ::get_cap_status_response* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void get_topk_result(::grpc::ClientContext* context, const ::empty_request* request, ::get_topk_result_response* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void get_topk_result(::grpc::ClientContext* context, const ::empty_request* request, ::get_topk_result_response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void get_topk_result(::grpc::ClientContext* context, const ::empty_request* request, ::get_topk_result_response* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::getif_response>* Asyncget_if_listRaw(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::getif_response>* PrepareAsyncget_if_listRaw(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::run_cap_response>* Asyncrun_captureRaw(::grpc::ClientContext* context, const ::run_cap_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::run_cap_response>* PrepareAsyncrun_captureRaw(::grpc::ClientContext* context, const ::run_cap_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::get_cap_status_response>* Asyncget_cap_statusRaw(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::get_cap_status_response>* PrepareAsyncget_cap_statusRaw(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::get_topk_result_response>* Asyncget_topk_resultRaw(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::get_topk_result_response>* PrepareAsyncget_topk_resultRaw(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status get_if_list(::grpc::ClientContext* context, const ::empty_request& request, ::getif_response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::getif_response>> Asyncget_if_list(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::getif_response>>(Asyncget_if_listRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::getif_response>> PrepareAsyncget_if_list(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::getif_response>>(PrepareAsyncget_if_listRaw(context, request, cq));
    }
    ::grpc::Status run_capture(::grpc::ClientContext* context, const ::run_cap_request& request, ::run_cap_response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::run_cap_response>> Asyncrun_capture(::grpc::ClientContext* context, const ::run_cap_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::run_cap_response>>(Asyncrun_captureRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::run_cap_response>> PrepareAsyncrun_capture(::grpc::ClientContext* context, const ::run_cap_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::run_cap_response>>(PrepareAsyncrun_captureRaw(context, request, cq));
    }
    ::grpc::Status get_cap_status(::grpc::ClientContext* context, const ::empty_request& request, ::get_cap_status_response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::get_cap_status_response>> Asyncget_cap_status(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::get_cap_status_response>>(Asyncget_cap_statusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::get_cap_status_response>> PrepareAsyncget_cap_status(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::get_cap_status_response>>(PrepareAsyncget_cap_statusRaw(context, request, cq));
    }
    ::grpc::Status get_topk_result(::grpc::ClientContext* context, const ::empty_request& request, ::get_topk_result_response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::get_topk_result_response>> Asyncget_topk_result(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::get_topk_result_response>>(Asyncget_topk_resultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::get_topk_result_response>> PrepareAsyncget_topk_result(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::get_topk_result_response>>(PrepareAsyncget_topk_resultRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void get_if_list(::grpc::ClientContext* context, const ::empty_request* request, ::getif_response* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void get_if_list(::grpc::ClientContext* context, const ::empty_request* request, ::getif_response* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void get_if_list(::grpc::ClientContext* context, const ::empty_request* request, ::getif_response* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void run_capture(::grpc::ClientContext* context, const ::run_cap_request* request, ::run_cap_response* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void run_capture(::grpc::ClientContext* context, const ::run_cap_request* request, ::run_cap_response* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void run_capture(::grpc::ClientContext* context, const ::run_cap_request* request, ::run_cap_response* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void get_cap_status(::grpc::ClientContext* context, const ::empty_request* request, ::get_cap_status_response* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void get_cap_status(::grpc::ClientContext* context, const ::empty_request* request, ::get_cap_status_response* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void get_cap_status(::grpc::ClientContext* context, const ::empty_request* request, ::get_cap_status_response* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void get_topk_result(::grpc::ClientContext* context, const ::empty_request* request, ::get_topk_result_response* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void get_topk_result(::grpc::ClientContext* context, const ::empty_request* request, ::get_topk_result_response* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void get_topk_result(::grpc::ClientContext* context, const ::empty_request* request, ::get_topk_result_response* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::getif_response>* Asyncget_if_listRaw(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::getif_response>* PrepareAsyncget_if_listRaw(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::run_cap_response>* Asyncrun_captureRaw(::grpc::ClientContext* context, const ::run_cap_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::run_cap_response>* PrepareAsyncrun_captureRaw(::grpc::ClientContext* context, const ::run_cap_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::get_cap_status_response>* Asyncget_cap_statusRaw(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::get_cap_status_response>* PrepareAsyncget_cap_statusRaw(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::get_topk_result_response>* Asyncget_topk_resultRaw(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::get_topk_result_response>* PrepareAsyncget_topk_resultRaw(::grpc::ClientContext* context, const ::empty_request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_get_if_list_;
    const ::grpc::internal::RpcMethod rpcmethod_run_capture_;
    const ::grpc::internal::RpcMethod rpcmethod_get_cap_status_;
    const ::grpc::internal::RpcMethod rpcmethod_get_topk_result_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status get_if_list(::grpc::ServerContext* context, const ::empty_request* request, ::getif_response* response);
    virtual ::grpc::Status run_capture(::grpc::ServerContext* context, const ::run_cap_request* request, ::run_cap_response* response);
    virtual ::grpc::Status get_cap_status(::grpc::ServerContext* context, const ::empty_request* request, ::get_cap_status_response* response);
    virtual ::grpc::Status get_topk_result(::grpc::ServerContext* context, const ::empty_request* request, ::get_topk_result_response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_get_if_list : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_get_if_list() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_get_if_list() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_if_list(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::getif_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_if_list(::grpc::ServerContext* context, ::empty_request* request, ::grpc::ServerAsyncResponseWriter< ::getif_response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_run_capture : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_run_capture() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_run_capture() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status run_capture(::grpc::ServerContext* /*context*/, const ::run_cap_request* /*request*/, ::run_cap_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestrun_capture(::grpc::ServerContext* context, ::run_cap_request* request, ::grpc::ServerAsyncResponseWriter< ::run_cap_response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_get_cap_status : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_get_cap_status() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_get_cap_status() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_cap_status(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::get_cap_status_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_cap_status(::grpc::ServerContext* context, ::empty_request* request, ::grpc::ServerAsyncResponseWriter< ::get_cap_status_response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_get_topk_result : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_get_topk_result() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_get_topk_result() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_topk_result(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::get_topk_result_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_topk_result(::grpc::ServerContext* context, ::empty_request* request, ::grpc::ServerAsyncResponseWriter< ::get_topk_result_response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_get_if_list<WithAsyncMethod_run_capture<WithAsyncMethod_get_cap_status<WithAsyncMethod_get_topk_result<Service > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_get_if_list : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_get_if_list() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::empty_request, ::getif_response>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::empty_request* request, ::getif_response* response) { return this->get_if_list(context, request, response); }));}
    void SetMessageAllocatorFor_get_if_list(
        ::grpc::experimental::MessageAllocator< ::empty_request, ::getif_response>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::empty_request, ::getif_response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_get_if_list() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_if_list(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::getif_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* get_if_list(
      ::grpc::CallbackServerContext* /*context*/, const ::empty_request* /*request*/, ::getif_response* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* get_if_list(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::empty_request* /*request*/, ::getif_response* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_run_capture : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_run_capture() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::run_cap_request, ::run_cap_response>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::run_cap_request* request, ::run_cap_response* response) { return this->run_capture(context, request, response); }));}
    void SetMessageAllocatorFor_run_capture(
        ::grpc::experimental::MessageAllocator< ::run_cap_request, ::run_cap_response>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::run_cap_request, ::run_cap_response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_run_capture() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status run_capture(::grpc::ServerContext* /*context*/, const ::run_cap_request* /*request*/, ::run_cap_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* run_capture(
      ::grpc::CallbackServerContext* /*context*/, const ::run_cap_request* /*request*/, ::run_cap_response* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* run_capture(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::run_cap_request* /*request*/, ::run_cap_response* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_get_cap_status : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_get_cap_status() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::empty_request, ::get_cap_status_response>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::empty_request* request, ::get_cap_status_response* response) { return this->get_cap_status(context, request, response); }));}
    void SetMessageAllocatorFor_get_cap_status(
        ::grpc::experimental::MessageAllocator< ::empty_request, ::get_cap_status_response>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::empty_request, ::get_cap_status_response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_get_cap_status() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_cap_status(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::get_cap_status_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* get_cap_status(
      ::grpc::CallbackServerContext* /*context*/, const ::empty_request* /*request*/, ::get_cap_status_response* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* get_cap_status(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::empty_request* /*request*/, ::get_cap_status_response* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_get_topk_result : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_get_topk_result() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::empty_request, ::get_topk_result_response>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::empty_request* request, ::get_topk_result_response* response) { return this->get_topk_result(context, request, response); }));}
    void SetMessageAllocatorFor_get_topk_result(
        ::grpc::experimental::MessageAllocator< ::empty_request, ::get_topk_result_response>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(3);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::empty_request, ::get_topk_result_response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_get_topk_result() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_topk_result(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::get_topk_result_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* get_topk_result(
      ::grpc::CallbackServerContext* /*context*/, const ::empty_request* /*request*/, ::get_topk_result_response* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* get_topk_result(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::empty_request* /*request*/, ::get_topk_result_response* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_get_if_list<ExperimentalWithCallbackMethod_run_capture<ExperimentalWithCallbackMethod_get_cap_status<ExperimentalWithCallbackMethod_get_topk_result<Service > > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_get_if_list<ExperimentalWithCallbackMethod_run_capture<ExperimentalWithCallbackMethod_get_cap_status<ExperimentalWithCallbackMethod_get_topk_result<Service > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_get_if_list : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_get_if_list() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_get_if_list() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_if_list(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::getif_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_run_capture : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_run_capture() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_run_capture() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status run_capture(::grpc::ServerContext* /*context*/, const ::run_cap_request* /*request*/, ::run_cap_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_get_cap_status : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_get_cap_status() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_get_cap_status() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_cap_status(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::get_cap_status_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_get_topk_result : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_get_topk_result() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_get_topk_result() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_topk_result(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::get_topk_result_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_get_if_list : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_get_if_list() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_get_if_list() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_if_list(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::getif_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_if_list(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_run_capture : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_run_capture() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_run_capture() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status run_capture(::grpc::ServerContext* /*context*/, const ::run_cap_request* /*request*/, ::run_cap_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestrun_capture(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_get_cap_status : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_get_cap_status() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_get_cap_status() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_cap_status(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::get_cap_status_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_cap_status(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_get_topk_result : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_get_topk_result() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_get_topk_result() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_topk_result(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::get_topk_result_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_topk_result(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_get_if_list : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_get_if_list() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->get_if_list(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_get_if_list() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_if_list(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::getif_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* get_if_list(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* get_if_list(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_run_capture : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_run_capture() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->run_capture(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_run_capture() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status run_capture(::grpc::ServerContext* /*context*/, const ::run_cap_request* /*request*/, ::run_cap_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* run_capture(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* run_capture(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_get_cap_status : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_get_cap_status() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->get_cap_status(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_get_cap_status() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_cap_status(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::get_cap_status_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* get_cap_status(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* get_cap_status(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_get_topk_result : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_get_topk_result() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->get_topk_result(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_get_topk_result() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_topk_result(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::get_topk_result_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* get_topk_result(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* get_topk_result(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_get_if_list : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_get_if_list() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::empty_request, ::getif_response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::empty_request, ::getif_response>* streamer) {
                       return this->Streamedget_if_list(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_get_if_list() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status get_if_list(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::getif_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedget_if_list(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::empty_request,::getif_response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_run_capture : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_run_capture() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::run_cap_request, ::run_cap_response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::run_cap_request, ::run_cap_response>* streamer) {
                       return this->Streamedrun_capture(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_run_capture() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status run_capture(::grpc::ServerContext* /*context*/, const ::run_cap_request* /*request*/, ::run_cap_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedrun_capture(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::run_cap_request,::run_cap_response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_get_cap_status : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_get_cap_status() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::empty_request, ::get_cap_status_response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::empty_request, ::get_cap_status_response>* streamer) {
                       return this->Streamedget_cap_status(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_get_cap_status() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status get_cap_status(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::get_cap_status_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedget_cap_status(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::empty_request,::get_cap_status_response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_get_topk_result : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_get_topk_result() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::empty_request, ::get_topk_result_response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::empty_request, ::get_topk_result_response>* streamer) {
                       return this->Streamedget_topk_result(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_get_topk_result() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status get_topk_result(::grpc::ServerContext* /*context*/, const ::empty_request* /*request*/, ::get_topk_result_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedget_topk_result(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::empty_request,::get_topk_result_response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_get_if_list<WithStreamedUnaryMethod_run_capture<WithStreamedUnaryMethod_get_cap_status<WithStreamedUnaryMethod_get_topk_result<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_get_if_list<WithStreamedUnaryMethod_run_capture<WithStreamedUnaryMethod_get_cap_status<WithStreamedUnaryMethod_get_topk_result<Service > > > > StreamedService;
};


#endif  // GRPC_tele_5fservice_2eproto__INCLUDED
